version: "3.8"

services:
  sales-api:
    container_name: sales-api
    build:
      context: .
      dockerfile: Dockerfile
    image: products-api:latest
    environment:
      - DATABASE_URL=jdbc:postgresql://sales-db:5432/postgres
      - PGUSER=postgres
      - PGPASSWORD=postgres
      - PORT=8080
    ports:
      - "8080:8080"
    restart: "on-failure"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 700M
      restart_policy:
        condition: on-failure
    depends_on:
      - sales-db
    networks:
      - graphql-network
      
  sales-db:
    container_name: sales-db
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - TZ=America/Sao_Paulo
    ports:
      - "5432:5432"
    restart: on-failure
    networks:
      - graphql-network

networks:
  graphql-network:
    name: graphql-network
    driver: bridge